export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_OK = "LOGIN_USER_OK";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const USER_LOG = "USER_LOG";
export const USER_LOG_OK = "USER_LOG_OK";
export const USER_LOG_ERROR = "USER_LOG_ERROR";

export const ADMIN_UPDATE = "ADMIN_UPDATE";
export const ADMIN_UPDATE_OK = "ADMIN_UPDATE_OK";
export const ADMIN_UPDATE_ERROR = "ADMIN_UPDATE_ERROR";

export const ADMIN_IMAGE = "ADMIN_IMAGE";
export const ADMIN_IMAGE_OK = "ADMIN_IMAGE_OK";
export const ADMIN_IMAGE_ERROR = "ADMIN_IMAGE_ERROR";

export const DNI = "DNI"
export const DNI_OK = "DNI_OK";
export const DNI_ERROR = "DNI_ERROR";

export const TOKEN_MASTER = "TOKEN_MASTER";
export const TOKEN_MASTER_OK = "TOKEN_MASTER_OK";
export const TOKEN_MASTER_ERROR = "TOKEN_MASTER_ERROR";

export const REGISTER_ADMIN = "REGISTER_ADMIN";
export const REGISTER_ADMIN_OK = "REGISTER_ADMIN_OK";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";

export const RUC = "RUC";
export const RUC_OK = "RUC_OK";
export const RUC_ERROR = "RUC_ERROR";

export const REGISTER_BUSINESS = "REGISTER_BUSINESS";
export const REGISTER_BUSINESS_OK = "REGISTER_BUSINESS_OK";
export const REGISTER_BUSINESS_ERROR = "REGISTER_BUSINESS_ERROR";

export const BUSINESS_ADMIN = "BUSINESS_ADMIN";
export const BUSINESS_ADMIN_OK = "BUSINESS_ADMIN_OK";
export const BUSINESS_ADMIN_ERROR = "BUSINESS_ADMIN_ERROR";

export const BUSINESS_EDIT = "BUSINESS_EDIT";
export const BUSINESS_EDIT_OK = "BUSINESS_EDIT_OK";
export const BUSINESS_EDIT_ERROR = "BUSINESS_EDIT_ERROR";

export const BUSINESS_IMAGE = "BUSINESS_IMAGE";
export const BUSINESS_IMAGE_OK ="BUSINESS_IMAGE_OK";
export const BUSINESS_IMAGE_ERROR = "BUSINESS_IMAGE_ERROR";

export const FILE_SALE = "FILE_SALE";
export const FILE_SALE_OK = "FILE_SALE_OK";
export const FILE_SALE_ERROR = "FILE_SALE_ERROR";

export const GET_FILES = "GET_FILES";
export const GET_FILES_OK = "GET_FILES_OK";
export const GET_FILES_ERROR = "GET_FILES_ERROR";

export const REGISTER_COMPETITION = "REGISTER_COMPETITION";
export const REGISTER_COMPETITION_OK = "REGISTER_COMPETITION_OK";
export const REGISTER_COMPETITION_ERROR = "REGISTER_COMPETITION_ERROR";

export const GET_COMPETITION = "GET_COMPETITION";
export const GET_COMPETITION_OK = "GET_COMPETITION_OK";
export const GET_COMPETITION_ERROR = "GET_COMPETITION_ERROR";

export const COMPETITION_IMAGE = "COMPETITION_IMAGE";
export const COMPETITION_IMAGE_OK = "COMPETITION_IMAGE_OK";
export const COMPETITION_IMAGE_ERROR = "COMPETITION_IMAGE_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_OK = "GET_CATEGORIES_OK";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const REGISTER_CATALOG = "REGISTER_CATALOG";
export const REGISTER_CATALOG_OK = "REGISTER_CATALOG_OK";
export const REGISTER_CATALOG_ERROR = "REGISTER_CATALOG_ERROR";

export const GET_PRIZES = "GET_PRIZES";
export const GET_PRIZES_OK = "GET_PRIZES_OK";
export const GET_PRIZES_ERROR = "GET_PRIZES_ERROR";